# Generated by Django 5.0.6 on 2025-11-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('FAULT_DETECTED', 'Fault Detected'), ('CHARGING_STOPPED', 'Charging Stopped'), ('THRESHOLDS_CHANGED', 'Thresholds Changed'), ('INFO', 'Info'), ('PREDICTION_ERROR', 'Prediction Error')], max_length=32)),
                ('details', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.FloatField()),
                ('voltage', models.FloatField()),
                ('temperature', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thresholds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_current', models.FloatField(default=10.0)),
                ('max_current', models.FloatField(default=30.0)),
                ('min_voltage', models.FloatField(default=400.0)),
                ('max_voltage', models.FloatField(default=460.0)),
                ('min_temperature', models.FloatField(default=0.0)),
                ('max_temperature', models.FloatField(default=80.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
