# Generated by Django 5.0.6 on 2025-09-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thresholds',
            name='max_current',
            field=models.FloatField(default=32.0),
        ),
        migrations.AlterField(
            model_name='thresholds',
            name='max_temperature',
            field=models.FloatField(default=60.0),
        ),
        migrations.AlterField(
            model_name='thresholds',
            name='max_voltage',
            field=models.FloatField(default=250.0),
        ),
        migrations.AlterField(
            model_name='thresholds',
            name='min_current',
            field=models.FloatField(default=6.0),
        ),
        migrations.AlterField(
            model_name='thresholds',
            name='min_voltage',
            field=models.FloatField(default=220.0),
        ),
    ]
