# Generated by Django 5.0.6 on 2025-09-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_thresholds_max_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thresholds',
            name='min_temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='thresholds',
            name='max_current',
            field=models.FloatField(default=30.0),
        ),
        migrations.AlterField(
            model_name='thresholds',
            name='max_temperature',
            field=models.FloatField(default=80.0),
        ),
        migrations.AlterField(
            model_name='thresholds',
            name='max_voltage',
            field=models.FloatField(default=460.0),
        ),
        migrations.AlterField(
            model_name='thresholds',
            name='min_current',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='thresholds',
            name='min_voltage',
            field=models.FloatField(default=400.0),
        ),
    ]
