# -*- coding: utf-8 -*-
"""EVOptima.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bT8qCfZ25hZGUlkIqUsPC7xP5VBJ0FMt
"""

!pip install xgboost



!pip install -U scikit-learn

# Import required libraries
import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from xgboost import XGBRegressor
import joblib

# Set random seed for reproducibility
np.random.seed(42)

df1 = pd.read_csv("/content/ev_charging_data1.csv")
df1.head()
df1.info()
df1.describe()

df2 = pd.read_csv("/content/ev_charging_data2_reordered.csv")
df2.head()
df2.info()
df2.describe()

import pandas as pd

df1 = pd.read_csv("/content/ev_charging_data1.csv")
df2 = pd.read_csv("/content/ev_charging_data2.csv")
df = pd.concat([df1, df2], ignore_index=True)

df.head()
df.info()
df.describe()

import pandas as pd

# Load both datasets
df1 = pd.read_csv("ev_charging_data1.csv")
df2 = pd.read_csv("ev_charging_data2.csv")

# Identify common and extra columns
common_columns = [col for col in df1.columns if col in df2.columns]
extra_columns_df2 = [col for col in df2.columns if col not in df1.columns]

# Reorder columns of df2
ordered_columns_df2 = common_columns + extra_columns_df2
df2_reordered = df2[ordered_columns_df2]

# Optional: Save the reordered DataFrame to a new CSV
df2_reordered.to_csv("ev_charging_data2_reordered.csv", index=False)

import pandas as pd

# Load the CSVs
df1 = pd.read_csv("ev_charging_data1.csv")
df2 = pd.read_csv("ev_charging_data2.csv")

# Columns to preview
columns = ["Timestamp", "Charging Power_kW", "Charging Voltage_V", "Charging Current_A", "Battery Temperature_C"]

# Preview first 5 rows
print("Data 1 Preview:")
print(df1[columns].head())

print("\nData 2 Preview:")
print(df2[columns].head())

import pandas as pd

# Load all CSVs
df1 = pd.read_csv("ev_charging_data1.csv")
df2 = pd.read_csv("ev_charging_data2.csv")
df3 = pd.read_csv("ev_charging_data2_reordered.csv")

# For demonstration, concatenate all data (adjust as needed for your analysis)
dfs = [df1, df2, df3]
for i, df in enumerate(dfs):
    df['source'] = f'df{i+1}'
df = pd.concat(dfs, ignore_index=True)
print("Combined shape:", df.shape)
df.head()

# Remove duplicates
df = df.drop_duplicates()

# Parse timestamp if present
if 'Timestamp' in df.columns:
    df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce')

# Handle missing values
missing_summary = df.isnull().sum()
print("Missing values per column:\n", missing_summary)

# Fill or drop missing values (choose strategy as needed)
df = df.fillna(df.median(numeric_only=True))  # Numeric columns
df = df.dropna(axis=0)  # Drop rows with remaining NaNs (e.g., in Timestamp)

# Reset index after cleaning
df = df.reset_index(drop=True)
print("Data shape after cleaning:", df.shape)

# Example: Extract hour and day of week from Timestamp
if 'Timestamp' in df.columns:
    df['hour'] = df['Timestamp'].dt.hour
    df['dayofweek'] = df['Timestamp'].dt.dayofweek

# Example: Rolling mean of Charging Power (window=5)
if 'Charging Power_kW' in df.columns:
    df['Charging_Power_RollingMean5'] = df['Charging Power_kW'].rolling(window=5, min_periods=1).mean()

# Add more features as needed for your analysis!
df.head()

from google.colab import drive
drive.mount('/content/drive')

"""# Task
Tell me about this dataset.

Here is all the data you need:
"ev_charging_data1.csv"
"ev_charging_data2.csv"

## Data loading

### Subtask:
Load the two datasets into pandas DataFrames.

**Reasoning**:
Load the two datasets into pandas DataFrames and display the first 5 rows of each to verify.
"""

import pandas as pd

try:
    df1 = pd.read_csv('ev_charging_data1.csv')
    df2 = pd.read_csv('ev_charging_data2.csv')
    display(df1.head())
    display(df2.head())
except FileNotFoundError:
    print("One or both of the CSV files were not found.")
except pd.errors.ParserError:
    print("There was an error parsing one or both of the CSV files.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

"""## Data exploration

### Subtask:
Explore the loaded datasets, `df1` and `df2`, to understand their characteristics.

**Reasoning**:
Explore the dataframes `df1` and `df2` by examining their shapes, data types, descriptive statistics, missing values, and common columns, as well as visualizing the distribution of key numerical columns.
"""

# Examine Data Shapes and Data Types
print("df1 shape:", df1.shape)
print("df1 data types:\n", df1.dtypes)
print("\ndf2 shape:", df2.shape)
print("df2 data types:\n", df2.dtypes)

# Descriptive Statistics
print("\ndf1 descriptive statistics:\n", df1.describe())
print("\ndf2 descriptive statistics:\n", df2.describe())

# Missing Values
print("\ndf1 missing values:\n", df1.isnull().sum())
print("\ndf2 missing values:\n", df2.isnull().sum())

# Common Columns
common_cols = list(set(df1.columns) & set(df2.columns))
print("\nCommon columns:", common_cols)

# Data Distribution (Histograms)
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))

plt.subplot(2, 2, 1)
plt.hist(df1['Charging Power_kW'], bins=20, color='skyblue', edgecolor='black')
plt.title('df1 Charging Power Distribution')
plt.xlabel('Charging Power (kW)')
plt.ylabel('Frequency')

plt.subplot(2, 2, 2)
plt.hist(df2['Charging Power_kW'], bins=20, color='salmon', edgecolor='black')
plt.title('df2 Charging Power Distribution')
plt.xlabel('Charging Power (kW)')
plt.ylabel('Frequency')

plt.subplot(2, 2, 3)
plt.hist(df1['Energy Supplied_kWh'], bins=20, color='lightgreen', edgecolor='black')
plt.title('df1 Energy Supplied Distribution')
plt.xlabel('Energy Supplied (kWh)')
plt.ylabel('Frequency')

plt.subplot(2, 2, 4)
plt.hist(df2['Energy Supplied_kWh'], bins=20, color='gold', edgecolor='black')
plt.title('df2 Energy Supplied Distribution')
plt.xlabel('Energy Supplied (kWh)')
plt.ylabel('Frequency')

plt.tight_layout()
plt.show()

# Initial Observations (will be printed after the code execution)

"""## Data preparation

### Subtask:
Combine the two dataframes, `df1` and `df2`, into a single dataframe named `combined_df`.

**Reasoning**:
Merge the two dataframes based on common columns, handle missing values, and rename columns as needed.  An inner merge is chosen to keep only the data points present in both datasets.
"""

# Merge the two dataframes
combined_df = pd.merge(df1, df2, on=['Timestamp', 'State Of Charge_SoC', 'Charging Power_kW', 'Charging Voltage_V', 'Charging Current_A', 'Battery Temperature_C', 'Vehicle Speed_kmh', 'Regenerative Power_kW', 'Energy Supplied_kWh', 'Motor RPM', 'Time Elapsed_s'], how='inner')

# Handle missing values (if any) - In this case, an inner join removes rows with mismatches, so no imputation needed.
# Check for missing values after the merge
print("Missing values in combined_df:\n", combined_df.isnull().sum())

# Rename columns if needed to avoid ambiguity and improve clarity
# Example: If there were duplicate column names after the merge, rename them here.  Since we used an inner merge on the common columns, there shouldn't be any duplicate columns with different meanings.
# combined_df = combined_df.rename(columns={'column_name_df1': 'new_column_name_1', 'column_name_df2': 'new_column_name_2'})

# Display the first few rows of the combined dataframe
display(combined_df.head())

"""**Reasoning**:
The previous inner merge resulted in an empty DataFrame, indicating no matching rows across all specified columns.  I will try to merge on fewer columns to see if there are some matches. Then I will handle missing values.


"""

# Merge the two dataframes on a smaller set of common columns.  Timestamp and Energy Supplied are likely to match better
combined_df = pd.merge(df1, df2, on=['Timestamp', 'Energy Supplied_kWh'], how='inner')

# Handle missing values (if any).  Since it's an inner join, only matching rows will be present.
# Check for missing values after the merge
print("Missing values in combined_df:\n", combined_df.isnull().sum())

# Rename columns to avoid ambiguity
# Example: Rename columns that might have the same name but different meanings in the original dataframes
# We can suffix the column names from df2 with "_df2" to avoid any naming conflicts
for col in df2.columns:
    if col in df1.columns and col not in ['Timestamp', 'Energy Supplied_kWh']:
        combined_df = combined_df.rename(columns={col: col + "_df2"})

display(combined_df.head())

"""## Data preparation

### Subtask:
Combine the two dataframes, `df1` and `df2`, into a single dataframe named `combined_df`.  Since a direct merge on common columns failed, we will explore alternative strategies.

**Reasoning**:
The previous attempts to merge the dataframes failed due to mismatches in the 'Timestamp' and other columns.  I will try to convert the 'Timestamp' columns to datetime objects to see if that helps with merging or to identify any issues in the timestamp formats. I will then attempt to merge on 'Timestamp' alone, followed by other strategies if that fails.  I will also check for duplicates after merging.
"""

import pandas as pd

# Convert 'Timestamp' columns to datetime objects
try:
    df1['Timestamp'] = pd.to_datetime(df1['Timestamp'], format='%d-%m-%Y %H:%M', errors='coerce')
    df2['Timestamp'] = pd.to_datetime(df2['Timestamp'], format='%d-%m-%Y %H:%M', errors='coerce')
except Exception as e:
    print(f"Error converting Timestamp columns to datetime: {e}")

# Check for any NaT values after conversion
print(f"Number of NaT values in df1['Timestamp']: {df1['Timestamp'].isna().sum()}")
print(f"Number of NaT values in df2['Timestamp']: {df2['Timestamp'].isna().sum()}")

# Attempt merging on 'Timestamp'
try:
    combined_df = pd.merge(df1, df2, on='Timestamp', how='inner')
except Exception as e:
    print(f"Error merging on 'Timestamp': {e}")


# Handle duplicates after merge if necessary
if 'combined_df' in locals():
    print(f"Number of duplicate timestamps in combined_df: {combined_df.duplicated(subset='Timestamp').sum()}")
    # If there are duplicates, group by timestamp and aggregate other columns (e.g., take the mean)
    if combined_df.duplicated(subset='Timestamp').sum() > 0:
        combined_df = combined_df.groupby('Timestamp').agg('mean').reset_index()

# If the merge on 'Timestamp' fails or produces unsatisfactory results, try other strategies
if 'combined_df' not in locals() or combined_df.empty:
    print("Merge on 'Timestamp' failed or produced an empty DataFrame. Trying other strategies...")
    # try other strategies here based on the results above...

# Display the first few rows and shape of the combined_df (if successful)
if 'combined_df' in locals() and not combined_df.empty:
    display(combined_df.head())
    print(combined_df.shape)
    print(combined_df.describe())
else:
    print("Unable to create a combined dataframe.")

"""**Reasoning**:
The previous merge attempts failed.  I will try concatenating the two dataframes, which might be more appropriate given the apparent lack of a suitable common key for merging.  I'll then handle any resulting duplicate rows and missing values, and finally verify the combined dataframe.


"""

# Concatenate the two dataframes
combined_df = pd.concat([df1, df2], ignore_index=True)

# Handle duplicates (if any)
if combined_df.duplicated().sum() > 0:
    print(f"Number of duplicate rows: {combined_df.duplicated().sum()}")
    # Remove duplicate rows based on all columns. If specific columns are of interest, specify subset
    combined_df = combined_df.drop_duplicates()

# Check for missing values after concatenation and deduplication
print(f"Number of missing values:\n{combined_df.isnull().sum()}")
# Handle missing values (if any)
# In this case, imputation or removal can be done based on the significance of missing values.
# For example, if the number of missing values is negligible, removal might be suitable.
# Otherwise, imputation strategies (e.g., mean, median, or more sophisticated methods) can be used.
# Below, I am removing all rows with missing values.
combined_df.dropna(inplace=True)


# Verify the result
if not combined_df.empty:
    display(combined_df.head())
    print(combined_df.shape)
    print(combined_df.describe())
else:
    print("Combined dataframe is empty after handling duplicates and missing values.")

"""**Reasoning**:
The `combined_df` has been created through concatenation.  The next step is to verify if the data types are consistent and correct, especially the `Timestamp` column.  Additionally, I will check for and handle any remaining missing values or duplicates that might have been introduced during concatenation. Then I will display the first few rows of `combined_df` and its shape. I will also check the summary statistics of `combined_df`.


"""

# Ensure data type consistency
combined_df['Timestamp'] = pd.to_datetime(combined_df['Timestamp'])

# Check for and handle any remaining missing values or duplicates
print(f"Number of missing values:\n{combined_df.isnull().sum()}")
combined_df.dropna(inplace = True)
print(f"Number of duplicates: {combined_df.duplicated().sum()}")
combined_df.drop_duplicates(inplace = True)

# Verify the combined dataframe
display(combined_df.head())
print(combined_df.shape)
print(combined_df.describe())

"""## Data analysis

### Subtask:
Analyze the combined dataset to understand the distribution of key variables and identify correlations.

**Reasoning**:
Calculate summary statistics, create histograms, calculate and visualize the correlation matrix, and investigate the relationship between charging time and energy supplied.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Summary Statistics
numerical_cols = combined_df.select_dtypes(include=['number']).columns
summary_stats = combined_df[numerical_cols].describe()
display(summary_stats)

# 2. Histograms
plt.figure(figsize=(15, 5))
plt.subplot(1, 3, 1)
plt.hist(combined_df['Charging Power_kW'], bins=20, color='skyblue', edgecolor='black')
plt.title('Charging Power Distribution')
plt.xlabel('Charging Power (kW)')
plt.ylabel('Frequency')

plt.subplot(1, 3, 2)
plt.hist(combined_df['Energy Supplied_kWh'], bins=20, color='salmon', edgecolor='black')
plt.title('Energy Supplied Distribution')
plt.xlabel('Energy Supplied (kWh)')
plt.ylabel('Frequency')

plt.subplot(1, 3, 3)
plt.hist(combined_df['Time Elapsed_s'], bins=20, color='lightgreen', edgecolor='black')
plt.title('Time Elapsed Distribution')
plt.xlabel('Time Elapsed (s)')
plt.ylabel('Frequency')

plt.tight_layout()
plt.show()


# 3. Correlation Matrix
correlation_matrix = combined_df[numerical_cols].corr()
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numerical Features')
plt.show()


# 4. Relationship between Charging Time and Energy Supplied
plt.figure(figsize=(8, 6))
plt.scatter(combined_df['Time Elapsed_s'], combined_df['Energy Supplied_kWh'], color='purple', alpha=0.5)
plt.title('Charging Time vs. Energy Supplied')
plt.xlabel('Time Elapsed (s)')
plt.ylabel('Energy Supplied (kWh)')
plt.show()

pearson_corr = combined_df['Time Elapsed_s'].corr(combined_df['Energy Supplied_kWh'])
print(f"Pearson correlation coefficient: {pearson_corr}")

"""## Data visualization

### Subtask:
Visualize key insights from the data analysis.

**Reasoning**:
Create the visualizations specified in the subtask instructions using the combined_df.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Histograms
plt.figure(figsize=(15, 5))
plt.subplot(1, 3, 1)
plt.hist(combined_df['Charging Power_kW'], bins=20, color='skyblue', edgecolor='black')
plt.title('Charging Power Distribution')
plt.xlabel('Charging Power (kW)')
plt.ylabel('Frequency')

plt.subplot(1, 3, 2)
plt.hist(combined_df['Energy Supplied_kWh'], bins=20, color='salmon', edgecolor='black')
plt.title('Energy Supplied Distribution')
plt.xlabel('Energy Supplied (kWh)')
plt.ylabel('Frequency')

plt.subplot(1, 3, 3)
plt.hist(combined_df['Time Elapsed_s'], bins=20, color='lightgreen', edgecolor='black')
plt.title('Time Elapsed Distribution')
plt.xlabel('Time Elapsed (s)')
plt.ylabel('Frequency')

plt.tight_layout()
plt.show()

# 2. Heatmap of Correlation Matrix
numerical_cols = combined_df.select_dtypes(include=['number']).columns
correlation_matrix = combined_df[numerical_cols].corr()
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numerical Features')
plt.show()

# 3. Scatter Plot: Time Elapsed vs. Energy Supplied
plt.figure(figsize=(8, 6))
plt.scatter(combined_df['Time Elapsed_s'], combined_df['Energy Supplied_kWh'], color='purple', alpha=0.5)
plt.title('Charging Time vs. Energy Supplied')
plt.xlabel('Time Elapsed (s)')
plt.ylabel('Energy Supplied (kWh)')

# Calculate and display Pearson correlation coefficient
pearson_corr = combined_df['Time Elapsed_s'].corr(combined_df['Energy Supplied_kWh'])
plt.text(0.05, 0.95, f"Pearson Correlation: {pearson_corr:.2f}", transform=plt.gca().transAxes)

plt.show()

# 4. Location-based Visualization (or Boxplot)
# Since there's no location information, create a boxplot for 'Energy Supplied_kWh' grouped by 'Charging Power_kW'
plt.figure(figsize=(10, 6))
sns.boxplot(x='Charging Power_kW', y='Energy Supplied_kWh', data=combined_df)
plt.title('Energy Supplied Distribution by Charging Power')
plt.xlabel('Charging Power (kW)')
plt.ylabel('Energy Supplied (kWh)')
plt.xticks(rotation=45, ha='right')
plt.show()



"""## Summary:

### 1. Q&A

* **What is the relationship between charging time and energy supplied?**  There is a very strong positive linear correlation between charging time ('Time Elapsed\_s') and energy supplied ('Energy Supplied\_kWh'), with a Pearson correlation coefficient of approximately 0.9997.  This indicates that as charging time increases, the energy supplied also increases almost proportionally.

### 2. Data Analysis Key Findings

* **Data Combination Challenges:** Initial attempts to merge the two datasets (`df1` and `df2`) using common columns failed due to inconsistencies.  Concatenation was used instead, followed by handling of duplicates and missing values.
* **Strong Correlation:**  A very strong positive correlation (Pearson coefficient ≈ 0.9997) exists between 'Time Elapsed\_s' and 'Energy Supplied\_kWh'.
* **Data Distribution:** Histograms show the distribution of key variables like 'Charging Power\_kW', 'Energy Supplied\_kWh', and 'Time Elapsed\_s'.  Further analysis of these distributions for potential outliers is recommended.
* **Combined Dataset Size:** The final combined dataset (`combined_df`) contains 9087 rows and 14 columns after handling duplicates and missing values.

### 3. Insights or Next Steps

* **Investigate Outliers:**  Examine the distributions of key variables (Charging Power, Energy Supplied, Time Elapsed) for potential outliers that could be skewing the analysis.
* **Explore Non-Linear Relationships:** While a strong linear correlation exists between charging time and energy supplied, explore potential non-linear relationships that might exist between other variables.

"""

import pandas as pd
import matplotlib.pyplot as plt

# Load your data
df = pd.read_csv("ev_charging_data1.csv")

# Convert 'Timestamp' to datetime with proper format
df['Timestamp'] = pd.to_datetime(df['Timestamp'], dayfirst=True)

# Plot: Timestamp vs Charging Parameters
plt.figure(figsize=(12, 6))
plt.plot(df['Timestamp'], df['Charging Power_kW'], label='Charging Power (kW)', color='blue')
plt.plot(df['Timestamp'], df['Charging Voltage_V'], label='Charging Voltage (V)', color='orange')
plt.plot(df['Timestamp'], df['Charging Current_A'], label='Charging Current (A)', color='green')
plt.plot(df['Timestamp'], df['Battery Temperature_C'], label='Battery Temp (°C)', color='red')

plt.xlabel('Timestamp')
plt.ylabel('Value')
plt.title('EV Charging Parameters Over Time')
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load and preprocess
df = pd.read_csv("ev_charging_data1.csv")
df['Timestamp'] = pd.to_datetime(df['Timestamp'], dayfirst=True)  # ✅ Fix applied here

# Apply smoothing (optional)
df['Power_Smoothed'] = df['Charging Power_kW'].rolling(window=10).mean()
df['Voltage_Smoothed'] = df['Charging Voltage_V'].rolling(window=10).mean()
df['Current_Smoothed'] = df['Charging Current_A'].rolling(window=10).mean()
df['Temp_Smoothed'] = df['Battery Temperature_C'].rolling(window=10).mean()

# Plotting using subplots
fig, axs = plt.subplots(4, 1, figsize=(14, 10), sharex=True)

axs[0].plot(df['Timestamp'], df['Power_Smoothed'], label='Power (kW)', color='blue')
axs[0].set_ylabel('Power (kW)')
axs[0].legend()
axs[0].grid(True)

axs[1].plot(df['Timestamp'], df['Voltage_Smoothed'], label='Voltage (V)', color='orange')
axs[1].set_ylabel('Voltage (V)')
axs[1].legend()
axs[1].grid(True)

axs[2].plot(df['Timestamp'], df['Current_Smoothed'], label='Current (A)', color='green')
axs[2].set_ylabel('Current (A)')
axs[2].legend()
axs[2].grid(True)

axs[3].plot(df['Timestamp'], df['Temp_Smoothed'], label='Battery Temp (°C)', color='red')
axs[3].set_ylabel('Temp (°C)')
axs[3].set_xlabel('Timestamp')
axs[3].legend()
axs[3].grid(True)

plt.suptitle('Smoothed EV Charging Parameters Over Time', fontsize=16)
plt.xticks(rotation=45)
plt.tight_layout(rect=[0, 0, 1, 0.97])
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load and preprocess
df = pd.read_csv("ev_charging_data2.csv")
df['Timestamp'] = pd.to_datetime(df['Timestamp'], dayfirst=True)  # ✅ Fix applied here

# Apply smoothing (optional)
df['Power_Smoothed'] = df['Charging Power_kW'].rolling(window=10).mean()
df['Voltage_Smoothed'] = df['Charging Voltage_V'].rolling(window=10).mean()
df['Current_Smoothed'] = df['Charging Current_A'].rolling(window=10).mean()
df['Temp_Smoothed'] = df['Battery Temperature_C'].rolling(window=10).mean()

# Plotting using subplots
fig, axs = plt.subplots(4, 1, figsize=(14, 10), sharex=True)

axs[0].plot(df['Timestamp'], df['Power_Smoothed'], label='Power (kW)', color='blue')
axs[0].set_ylabel('Power (kW)')
axs[0].legend()
axs[0].grid(True)

axs[1].plot(df['Timestamp'], df['Voltage_Smoothed'], label='Voltage (V)', color='orange')
axs[1].set_ylabel('Voltage (V)')
axs[1].legend()
axs[1].grid(True)

axs[2].plot(df['Timestamp'], df['Current_Smoothed'], label='Current (A)', color='green')
axs[2].set_ylabel('Current (A)')
axs[2].legend()
axs[2].grid(True)

axs[3].plot(df['Timestamp'], df['Temp_Smoothed'], label='Battery Temp (°C)', color='red')
axs[3].set_ylabel('Temp (°C)')
axs[3].set_xlabel('Timestamp')
axs[3].legend()
axs[3].grid(True)

plt.suptitle('Smoothed EV Charging Parameters Over Time', fontsize=16)
plt.xticks(rotation=45)
plt.tight_layout(rect=[0, 0, 1, 0.97])
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load your data
df = pd.read_csv("ev_charging_data2.csv")

# Convert 'Timestamp' to datetime correctly
df['Timestamp'] = pd.to_datetime(df['Timestamp'], dayfirst=True)

# Plot: Timestamp vs Charging Power
plt.figure(figsize=(12, 6))
plt.plot(df['Timestamp'], df['Charging Power_kW'], label='Charging Power (kW)', color='blue')
plt.plot(df['Timestamp'], df['Charging Voltage_V'], label='Charging Voltage (V)', color='orange')
plt.plot(df['Timestamp'], df['Charging Current_A'], label='Charging Current (A)', color='green')
plt.plot(df['Timestamp'], df['Battery Temperature_C'], label='Battery Temp (°C)', color='red')

plt.xlabel('Timestamp')
plt.ylabel('Value')
plt.title('EV Charging Parameters Over Time')
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.grid(True)
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

try:
    from xgboost import XGBRegressor
except ImportError:
    XGBRegressor = None
    print("XGBoost is not installed. Please install it using '!pip install xgboost'.")

# Select features and target
target = 'Charging Power_kW'
features = [col for col in df.columns if col not in ['Timestamp', 'source', target]]

# Only keep numeric features
X = df[features].select_dtypes(include='number')
y = df[target]

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train models
models = {
    "RandomForest": RandomForestRegressor(n_estimators=100, random_state=42),
    "LinearRegression": LinearRegression()
}
if XGBRegressor is not None:
    models["XGBoost"] = XGBRegressor(n_estimators=100, random_state=42)

results = {}
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    results[name] = {
        "model": model,
        "rmse": mean_squared_error(y_test, y_pred) ** 0.5,  # <-- Fixed here
        "r2": r2_score(y_test, y_pred)
    }
    print(f"{name}: RMSE={results[name]['rmse']:.4f}, R2={results[name]['r2']:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns

# Model performance comparison
model_names = list(results.keys())
rmses = [results[n]['rmse'] for n in model_names]
r2s = [results[n]['r2'] for n in model_names]

plt.figure(figsize=(8,4))
plt.subplot(1,2,1)
sns.barplot(x=model_names, y=rmses)
plt.title("RMSE by Model")
plt.subplot(1,2,2)
sns.barplot(x=model_names, y=r2s)
plt.title("R2 Score by Model")
plt.tight_layout()
plt.show()

# Feature importance for tree-based models
for name in ['RandomForest', 'XGBoost']:
    if name in results:
        model = results[name]['model']
        importances = model.feature_importances_
        indices = importances.argsort()[::-1]
        plt.figure(figsize=(10,5))
        plt.title(f"{name} Feature Importances")
        sns.barplot(x=X.columns[indices], y=importances[indices])
        plt.xticks(rotation=45)
        plt.show()

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from xgboost import XGBRegressor

# Load datasets
df1 = pd.read_csv("ev_charging_data1.csv")
df2 = pd.read_csv("ev_charging_data2.csv")
df3 = pd.read_csv("ev_charging_data2_reordered.csv")

# Define base and extra columns
base_columns = df1.columns.tolist()
extra_columns = ['Time-lap', 'Battery Voltage_BV', 'Battery Current_IB']

# Ensure all DataFrames have all required columns
for col in extra_columns:
    for df in [df1, df2, df3]:
        if col not in df.columns:
            df[col] = np.nan  # Use NaN instead of None

# Reorder columns to match df1 + extra columns
final_columns = base_columns + [col for col in extra_columns if col not in base_columns]
df1 = df1[final_columns]
df2 = df2[final_columns]
df3 = df3[final_columns]

# Merge the datasets
merged_df = pd.concat([df1, df2, df3], ignore_index=True)

# Feature engineering: derived feature
merged_df.loc[:, 'Current_Temp_Ratio'] = merged_df['Charging Current_A'] / (merged_df['Battery Temperature_C'] + 1)

# Define target columns
target_columns = [
    'Charging Current_A',
    'Charging Voltage_V',
    'Charging Power_kW',
    'Battery Temperature_C'
]

# Prepare features and remove non-numeric data
X = merged_df.drop(columns=['Timestamp'] + target_columns)
X = X.select_dtypes(include=[np.number])  # Keep only numeric columns

# Dictionary to store trained models and performance results
models = {}
results = {}

# Train XGBoost for each target
for target in target_columns:
    y = merged_df[target]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    model = XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))  # Fix for squared=False
    r2 = r2_score(y_test, y_pred)

    models[target] = model
    results[target] = {'RMSE': rmse, 'R2 Score': r2}

# Show evaluation results
for target, metrics in results.items():
    print(f"\nTarget: {target}")
    print(f"  ➤ RMSE: {metrics['RMSE']:.4f}")
    print(f"  ➤ R2 Score: {metrics['R2 Score']:.4f}")

print(df.columns.tolist())

import pandas as pd

# Load the datasets
df1 = pd.read_csv("ev_charging_data1.csv")
df2 = pd.read_csv("ev_charging_data2.csv")

# Align columns: Union of all columns from both
all_columns = sorted(set(df1.columns).union(df2.columns))

# Reindex both DataFrames with all columns
df1_aligned = df1.reindex(columns=all_columns)
df2_aligned = df2.reindex(columns=all_columns)

# Concatenate without losing any data
merged_df = pd.concat([df1_aligned, df2_aligned], ignore_index=True)

# Optional: Save merged data
merged_df.to_csv("ev_charging_merged.csv", index=False)

# Show the result
print("Merged DataFrame shape:", merged_df.shape)
print("Columns:", merged_df.columns.tolist())

import pandas as pd

df1 = pd.read_csv("ev_charging_data1.csv")
df2 = pd.read_csv("ev_charging_data2.csv")

print("Columns in DataSet 1:")
print(df1.columns.tolist())

print("\nColumns in DataSet 2:")
print(df2.columns.tolist())

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from xgboost import XGBRegressor

# Load the datasets
df1 = pd.read_csv("ev_charging_data1.csv")
df2 = pd.read_csv("ev_charging_data2.csv")

# Standardize column names for merging
df1.columns = df1.columns.str.strip()
df2.columns = df2.columns.str.strip()

# Define standard column set (based on union of both datasets)
standard_columns = list(set(df1.columns).union(set(df2.columns)))

# Ensure all DataFrames have the same structure
for col in standard_columns:
    if col not in df1.columns:
        df1[col] = np.nan
    if col not in df2.columns:
        df2[col] = np.nan

# Reorder columns
df1 = df1[standard_columns]
df2 = df2[standard_columns]

# Merge the datasets
merged_df = pd.concat([df1, df2], ignore_index=True)

# Convert appropriate columns to numeric
merged_df = merged_df.apply(pd.to_numeric, errors='coerce')

# Drop rows with missing critical values
merged_df.dropna(subset=['Charging Current_A', 'Battery Temperature_C'], inplace=True)

# Add derived feature
merged_df['Current_Temp_Ratio'] = merged_df['Charging Current_A'] / (merged_df['Battery Temperature_C'] + 1)

# Define target outputs
target_columns = ['Charging Current_A', 'Charging Voltage_V', 'Charging Power_kW', 'Battery Temperature_C']

# Prepare features
drop_cols = ['Timestamp'] if 'Timestamp' in merged_df.columns else []
drop_cols += target_columns
X = merged_df.drop(columns=drop_cols, errors='ignore')
X = X.select_dtypes(include=[np.number])  # Use only numeric features

# Train and evaluate XGBoost for each target
models = {}
results = {}

for target in target_columns:
    y = merged_df[target]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    model = XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    rmse = mean_squared_error(y_test, y_pred)  # RMSE
    r2 = r2_score(y_test, y_pred)

    models[target] = model
    results[target] = {'RMSE': rmse, 'R2 Score': r2}

# Display performance
import pprint
pprint.pprint(results)

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import mean_squared_error, classification_report
from sklearn.preprocessing import StandardScaler
import joblib

# Load data
df = pd.read_csv('/content/ev_charging_data2.csv')  # Update if needed

# Convert timestamp to datetime and extract features
# Convert timestamp to datetime and extract features
df['Timestamp'] = pd.to_datetime(df['Timestamp'], dayfirst=True)
df['Hour'] = df['Timestamp'].dt.hour
df['Day'] = df['Timestamp'].dt.dayofweek
df['Month'] = df['Timestamp'].dt.month
df['Is_Weekend'] = df['Day'].isin([5, 6]).astype(int)

# Drop unnecessary columns if they exist
df.drop(columns=[col for col in ['Timestamp', 'Charging_Point_ID'] if col in df.columns], inplace=True)


# Fill or drop missing values
df.dropna(inplace=True)

# ----------------------------
# ⚡ Regression: Predict Power
# ----------------------------
features_power = ['Charging Current_A', 'Charging Voltage_V', 'Battery Temperature_C',
                  'State Of Charge_SoC', 'Hour', 'Day', 'Month', 'Is_Weekend']
target_power = 'Charging Power_kW'


X_power = df[features_power]
y_power = df[target_power]

scaler_power = StandardScaler()
X_power_scaled = scaler_power.fit_transform(X_power)

X_train_p, X_test_p, y_train_p, y_test_p = train_test_split(X_power_scaled, y_power, test_size=0.2, random_state=42)

reg_model = RandomForestRegressor(n_estimators=100, random_state=42)
reg_model.fit(X_train_p, y_train_p)

y_pred_p = reg_model.predict(X_test_p)
mse = mean_squared_error(y_test_p, y_pred_p)
print(f"🔋 Regression MSE (Power): {mse:.2f}")

# ----------------------------
# 🚨 Classification: Fault Detection
# ----------------------------
features_fault = features_power
target_fault = 'Fault'  # 0 for OK, 1 for Faulty

X_fault = df[features_fault]
y_fault = df[target_fault]

scaler_fault = StandardScaler()
X_fault_scaled = scaler_fault.fit_transform(X_fault)

X_train_f, X_test_f, y_train_f, y_test_f = train_test_split(X_fault_scaled, y_fault, test_size=0.2, random_state=42)

clf_fault = RandomForestClassifier(n_estimators=100, random_state=42)
clf_fault.fit(X_train_f, y_train_f)

y_pred_f = clf_fault.predict(X_test_f)
print("⚠️ Fault Detection Report:")
print(classification_report(y_test_f, y_pred_f))

# -----------------------------------
# ⚡🔌 Classifier: 9th Charger Decision
# -----------------------------------
features_ninth = features_power + [target_power]

target_ninth = 'Ninth_Charger_Request'  # 1 for Allow, 0 for Deny

if target_ninth in df.columns:
    X_ninth = df[features_ninth]
    y_ninth = df[target_ninth]

    scaler_ninth = StandardScaler()
    X_ninth_scaled = scaler_ninth.fit_transform(X_ninth)

    X_train_n, X_test_n, y_train_n, y_test_n = train_test_split(X_ninth_scaled, y_ninth, test_size=0.2, random_state=42)

    clf_ninth = RandomForestClassifier(n_estimators=100, random_state=42)
    clf_ninth.fit(X_train_n, y_train_n)

    y_pred_n = clf_ninth.predict(X_test_n)
    print("🔌 9th Charger Decision Report:")
    print(classification_report(y_test_n, y_pred_n))

# -----------------------
# 💾 Save Models & Scalers
# -----------------------
joblib.dump(reg_model, 'power_regressor.joblib')
joblib.dump(scaler_power, 'scaler_power.joblib')
joblib.dump(clf_fault, 'fault_classifier.joblib')
joblib.dump(scaler_fault, 'scaler_fault.joblib')
if target_ninth in df.columns:
    joblib.dump(clf_ninth, 'ninth_charger_classifier.joblib')
    joblib.dump(scaler_ninth, 'scaler_ninth.joblib')

print("✅ Models and scalers saved successfully.")

import pandas as pd
import numpy as np
import joblib

# Load pre-trained model and scaler
# If the model was saved in a different path, update the file path here
model = joblib.load('/content/model.joblib')  # Assuming it was saved in the '/content' directory
scaler = joblib.load('/content/scaler.joblib') # Assuming it was saved in the '/content' directory

# ... (Rest of your code) ...

# Function to make prediction
def predict_energy_consumption(charging_power, battery_temp, soc, duration, timestamp):
    features = pd.DataFrame({
        'Charging Power_kW': [charging_power],
        'Battery Temperature_C': [battery_temp],
        'State Of Charge_SoC': [soc],
        'Charging_Duration_h': [duration],
        'hour': [timestamp.hour],
        'day_of_week': [timestamp.dayofweek],
        'month': [timestamp.month],
        'is_weekend': [1 if timestamp.dayofweek in [5, 6] else 0]
    })

    features_scaled = scaler.transform(features)
    prediction = model.predict(features_scaled)[0]
    return prediction

# Example use
example_timestamp = pd.Timestamp('2025-04-06 14:00:00')
predicted_energy = predict_energy_consumption(
    charging_power=50.0,
    battery_temp=25.0,
    soc=50.0,
    duration=1.0,
    timestamp=example_timestamp
)
print(f"Predicted energy consumption: {predicted_energy:.2f} kWh")

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from xgboost import XGBRegressor  # Make sure XGBoost is installed

# 1. Load and Preprocess Data (Similar to your previous steps)
df1 = pd.read_csv("ev_charging_data1.csv")
df2 = pd.read_csv("ev_charging_data2.csv")

# Standardize column names for merging
df1.columns = df1.columns.str.strip()
df2.columns = df2.columns.str.strip()

# Define standard column set (based on union of both datasets)
standard_columns = list(set(df1.columns).union(set(df2.columns)))

# Ensure all DataFrames have the same structure
for col in standard_columns:
    if col not in df1.columns:
        df1[col] = np.nan
    if col not in df2.columns:
        df2[col] = np.nan

# Reorder columns
df1 = df1[standard_columns]
df2 = df2[standard_columns]

# Merge the datasets
df = pd.concat([df1, df2], ignore_index=True) # Assign the merged dataframe to 'df'

# Convert appropriate columns to numeric
df = df.apply(pd.to_numeric, errors='coerce')

# Drop rows with missing critical values
df.dropna(subset=['Charging Current_A', 'Battery Temperature_C'], inplace=True)

# Add derived feature
df['Current_Temp_Ratio'] = df['Charging Current_A'] / (df['Battery Temperature_C'] + 1)


# 2. Train and Evaluate Models (This part was missing)
# Select features and target
target = 'Charging Power_kW'
features = [col for col in df.columns if col not in ['Timestamp', 'source', target]]
X = df[features].select_dtypes(include='number')
y = df[target]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train RandomForest model
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

# Store results
results = {  # Initialize the 'results' dictionary
    'RandomForest': {
        'model': rf_model,
        'rmse': np.sqrt(mean_squared_error(y_test, y_pred_rf)),  # Calculate RMSE using NumPy
        'r2': r2_score(y_test, y_pred_rf)
    }
}
print(f"RandomForest: RMSE={results['RandomForest']['rmse']:.4f}, R2={results['RandomForest']['r2']:.4f}")

# 3. Charger Prediction Logic
# ... (Rest of your charger prediction code) ...

import numpy as np
import pandas as pd

# Simulate per-charger data (assuming all chargers are similar for demonstration)
# In real use, structure your data so each charger has its own row or features
n_chargers = 8
sample_idx = -1  # Use the last row as "current" reading; change as needed

# Load your combined DataFrame (replace with appropriate path)
combined_df = pd.read_csv("ev_charging_data2.csv") # Assuming you saved your merged data to 'ev_charging_merged.csv'

# Features to predict for each charger (using your trained RandomForest model)
features = [col for col in combined_df.columns if col not in ['Timestamp', 'source', 'Charging Power_kW']]
X_sample = combined_df[features].iloc[[sample_idx]].select_dtypes(include='number')

# Predict for all chargers (using the same model and input for demo; replace with per-charger data if available)
predicted_power = results['RandomForest']['model'].predict(X_sample)[0]
# For demonstration, simulate other parameters as proportional to power
predicted_voltage = X_sample['Charging Voltage_V'].values[0] if 'Charging Voltage_V' in X_sample else 400
predicted_current = X_sample['Charging Current_A'].values[0] if 'Charging Current_A' in X_sample else 16
predicted_temp = X_sample['Battery Temperature_C'].values[0] if 'Battery Temperature_C' in X_sample else 30

# Fault detection placeholder (replace with your classifier if available)
def detect_fault(power, current, temp):
    # Example rule: if temp > 40 or power < 0.5, flag as FAULTY
    if temp > 40 or power < 0.5:
        return "FAULTY"
    return "OK"

# System-wide outputs
transformer_capacity = 100  # Example total capacity in kW
total_predicted_load = predicted_power * n_chargers
ninth_charger_request = True  # Simulate a request

if ninth_charger_request:
    if total_predicted_load + predicted_power < transformer_capacity:
        ninth_decision = "ALLOW"
    else:
        ninth_decision = "DISCONNECT"
else:
    ninth_decision = "N/A"

# Print system output
print("System Output:\n")
for i in range(1, n_chargers + 1):
    status = detect_fault(predicted_power, predicted_current, predicted_temp)
    print(f"Charger {i}: Power={predicted_power:.2f} kW, Voltage={predicted_voltage:.2f} V, "
          f"Current={predicted_current:.2f} A, Temp={predicted_temp:.2f}°C, Status={status}")

print(f"\nTotal Predicted Load: {total_predicted_load:.2f} kW")
print(f"9th Charger Connection Request: {'YES' if ninth_charger_request else 'NO'}")
print(f"9th Charger Decision: {ninth_decision}")

import numpy as np
import pandas as pd

# Parameters
n_chargers = 8
sample_idx = -1  # Use the last row
transformer_capacity = 100  # in kW
ninth_charger_request = True

# Load CSV
combined_df = pd.read_csv("ev_charging_data2.csv")

# Recreate required derived features
if 'Current_Temp_Ratio' not in combined_df.columns:
    if 'Charging Current_A' in combined_df.columns and 'Battery Temperature_C' in combined_df.columns:
        combined_df['Current_Temp_Ratio'] = combined_df['Charging Current_A'] / (combined_df['Battery Temperature_C'] + 1e-5)
    else:
        raise ValueError("Required columns for 'Current_Temp_Ratio' are missing.")

# Extract numeric features (excluding labels/timestamps)
features = [col for col in combined_df.columns if col not in ['Timestamp', 'source', 'Charging Power_kW']]
X_sample = combined_df[features].iloc[[sample_idx]].select_dtypes(include='number')

# Predict charging power
predicted_power = results['RandomForest']['model'].predict(X_sample)[0]

# Get supporting values
predicted_voltage = X_sample.get('Charging Voltage_V', pd.Series([400])).values[0]
predicted_current = X_sample.get('Charging Current_A', pd.Series([16])).values[0]
predicted_temp = X_sample.get('Battery Temperature_C', pd.Series([30])).values[0]

# Fault detection logic
def detect_fault(power, current, temp):
    return "FAULTY" if temp > 40 or power < 0.5 else "OK"

# Decision logic for 9th charger
total_predicted_load = predicted_power * n_chargers
if ninth_charger_request:
    ninth_decision = "ALLOW" if total_predicted_load + predicted_power < transformer_capacity else "DISCONNECT"
else:
    ninth_decision = "N/A"

# Output result
print("System Output:\n")
for i in range(1, n_chargers + 1):
    status = detect_fault(predicted_power, predicted_current, predicted_temp)
    print(f"Charger {i}: Power={predicted_power:.2f} kW, Voltage={predicted_voltage:.2f} V, "
          f"Current={predicted_current:.2f} A, Temp={predicted_temp:.2f}°C, Status={status}")

print(f"\nTotal Predicted Load: {total_predicted_load:.2f} kW")
print(f"9th Charger Connection Request: {'YES' if ninth_charger_request else 'NO'}")
print(f"9th Charger Decision: {ninth_decision}")

import numpy as np

# Use df3 as it contains the reordered and likely finalized data
df = df3.copy()

# Define the number of chargers in the system
n_chargers = 8
sample_idx = -1  # Use the latest row (can be changed for testing)

# Select features for prediction, excluding non-numeric and target columns
features = [col for col in df.columns if col not in ['Timestamp', 'source', 'Charging Power_kW']]
X_sample = df[features].iloc[[sample_idx]].select_dtypes(include='number')

# Predict power using trained model
predicted_power = results['RandomForest']['model'].predict(X_sample)[0]

# Simulate other parameters from the same row or use fallback
predicted_voltage = X_sample['Charging Voltage_V'].values[0] if 'Charging Voltage_V' in X_sample else 400
predicted_current = X_sample['Charging Current_A'].values[0] if 'Charging Current_A' in X_sample else 16
predicted_temp = X_sample['Battery Temperature_C'].values[0] if 'Battery Temperature_C' in X_sample else 30

# Fault detection logic (can be replaced with ML model too)
def detect_fault(power, current, temp):
    if temp > 40 or power < 0.5:
        return "FAULTY"
    return "OK"

# Transformer constraints and logic for 9th charger
transformer_capacity = 100  # in kW
total_predicted_load = predicted_power * n_chargers
ninth_charger_request = True

if ninth_charger_request:
    if total_predicted_load + predicted_power < transformer_capacity:
        ninth_decision = "ALLOW"
    else:
        ninth_decision = "DISCONNECT"
else:
    ninth_decision = "N/A"

# Output the predictions per charger
print("System Output:\n")
for i in range(1, n_chargers + 1):
    status = detect_fault(predicted_power, predicted_current, predicted_temp)
    print(f"Charger {i}: Power={predicted_power:.2f} kW, Voltage={predicted_voltage:.2f} V, "
          f"Current={predicted_current:.2f} A, Temp={predicted_temp:.2f}°C, Status={status}")

print(f"\nTotal Predicted Load: {total_predicted_load:.2f} kW")
print(f"9th Charger Connection Request: {'YES' if ninth_charger_request else 'NO'}")
print(f"9th Charger Decision: {ninth_decision}")

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Load your data (make sure the file paths are correct)
df1 = pd.read_csv("ev_charging_data1.csv")
df2 = pd.read_csv("ev_charging_data2.csv")

# Preprocess the data (as you did before)
# ... (Your data preprocessing code here) ...

# Train the RandomForest model (as you did before)
# ... (Your model training code here) ...

# Now you have the 'results' dictionary
# ... (Your charger prediction code, starting from here) ...
df = pd.read_csv("ev_charging_data2.csv") # Assuming you saved your merged data to 'ev_charging_merged.csv'
# Simulate per-charger data (assuming all chargers are similar for demonstration)
# In real use, structure your data so each charger has its own row or features
n_chargers = 8
sample_idx = -1  # Use the last row as "current" reading; change as needed

# Features to predict for each charger (using your trained RandomForest model)
features = [col for col in df.columns if col not in ['Timestamp', 'source', 'Charging Power_kW']]
X_sample = df[features].iloc[[sample_idx]].select_dtypes(include='number')

# Predict for all chargers (using the same model and input for demo; replace with per-charger data if available)
predicted_power = results['RandomForest']['model'].predict(X_sample)[0]
# For demonstration, simulate other parameters as proportional to power
predicted_voltage = X_sample['Charging Voltage_V'].values[0] if 'Charging Voltage_V' in X_sample else 400
predicted_current = X_sample['Charging Current_A'].values[0] if 'Charging Current_A' in X_sample else 16
predicted_temp = X_sample['Battery Temperature_C'].values[0] if 'Battery Temperature_C' in X_sample else 30

# Fault detection placeholder (replace with your classifier if available)
def detect_fault(power, current, temp):
    # Example rule: if temp > 40 or power < 0.5, flag as FAULTY
    if temp > 40 or power < 0.5:
        return "FAULTY"
    return "OK"

# System-wide outputs
transformer_capacity = 100  # Example total capacity in kW
total_predicted_load = predicted_power * n_chargers
ninth_charger_request = True  # Simulate a request

if ninth_charger_request:
    if total_predicted_load + predicted_power < transformer_capacity:
        ninth_decision = "ALLOW"
    else:
        ninth_decision = "DISCONNECT"
else:
    ninth_decision = "N/A"

# Print system output
print("System Output:\n")
for i in range(1, n_chargers + 1):
    status = detect_fault(predicted_power, predicted_current, predicted_temp)
    print(f"Charger {i}: Power={predicted_power:.2f} kW, Voltage={predicted_voltage:.2f} V, "
          f"Current={predicted_current:.2f} A, Temp={predicted_temp:.2f}°C, Status={status}")

print(f"\nTotal Predicted Load: {total_predicted_load:.2f} kW")
print(f"9th Charger Connection Request: {'YES' if ninth_charger_request else 'NO'}")
print(f"9th Charger Decision: {ninth_decision}")