# Generated by Django 5.2.15 on 2026-09-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_type', models.CharField(blank=True, choices=[('normal', 'Normal charging'), ('fault', 'Fault detection')], default='', max_length=16)),
                ('active_type', models.CharField(blank=True, choices=[('normal', 'Normal charging'), ('fault', 'Fault detection')], default='', max_length=16)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'simulation control',
            },
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(choices=[('FAULT_DETECTED', 'Fault Detected'), ('CHARGING_STOPPED', 'Charging Stopped'), ('THRESHOLDS_CHANGED', 'Thresholds Changed'), ('INFO', 'Info'), ('PREDICTION_ERROR', 'Prediction Error'), ('EMAIL_ERROR', 'Email Error')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='reading',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
